export const LOAD_LIST_START = 'LOAD_LIST_START'
export const LOAD_LIST_DONE = 'LOAD_LIST_DONE'
export const LOAD_LIST_ERROR = 'LOAD_LIST_ERROR'

export const LOAD_ITEM_START = 'LOAD_ITEM_START'
export const LOAD_ITEM_DONE = 'LOAD_ITEM_DONE'
export const LOAD_ITEM_ERROR = 'LOAD_ITEM_ERROR'

export const LOAD_COMMENTS_START = 'LOAD_COMMENTS_START'
export const LOAD_COMMENTS_DONE = 'LOAD_COMMENTS_DONE'
export const LOAD_COMMENTS_ERROR = 'LOAD_COMMENTS_ERROR'

export const LOAD_USER_START = 'LOAD_USER_START'
export const LOAD_USER_DONE = 'LOAD_USER_DONE'
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR'